require(rgeos)
require(maptools)
require(RCurl)
require(parallel)

library(raster)
library(rgdal)
library(maptool)

setwd('C:/Users/Thadeu Sobral/Desktop/PR')

asc <- list.files(pattern='.asc')
asc.s <-stack(asc)

myshp <- readOGR("Parana_Municipios.shp", layer= "Parana_Municipios")
extent(myshp)
e <- extent(myshp)
plot(myshp)

myraster.crop <- crop(asc.s, e, snap="out")
myraster.crop.s <- stack(myraster.crop)
plot(myraster.crop.s)

crop <- setValues(myraster.crop, NA)
myshp.r <- rasterize(myshp, crop)
myraster.masked <- mask(x=myraster.crop, mask=myshp.r)

myraster.masked.s <- stack (myraster.masked)
plot(myraster.masked.s)

writeRaster(myraster.masked.s$alt, 'Pr_alt.asc', format='ascii')
writeRaster(myraster.masked.s$bio_1, 'Pr_bio_1.asc', format='ascii')
writeRaster(myraster.masked.s$bio_2, 'Pr_bio_2.asc', format='ascii')
writeRaster(myraster.masked.s$bio_3, 'Pr_bio_3.asc', format='ascii')
writeRaster(myraster.masked.s$bio_4, 'Pr_bio_4.asc', format='ascii')
writeRaster(myraster.masked.s$bio_5, 'Pr_bio_5.asc', format='ascii')
writeRaster(myraster.masked.s$bio_6, 'Pr_bio_6.asc', format='ascii')
writeRaster(myraster.masked.s$bio_7, 'Pr_bio_7.asc', format='ascii')
writeRaster(myraster.masked.s$bio_8, 'Pr_bio_8.asc', format='ascii')
writeRaster(myraster.masked.s$bio_9, 'Pr_bio_9.asc', format='ascii')
writeRaster(myraster.masked.s$bio_10, 'Pr_bio_10.asc', format='ascii')
writeRaster(myraster.masked.s$bio_11, 'Pr_bio_11.asc', format='ascii')
writeRaster(myraster.masked.s$bio_12, 'Pr_bio_12.asc', format='ascii')
writeRaster(myraster.masked.s$bio_13, 'Pr_bio_13.asc', format='ascii')
writeRaster(myraster.masked.s$bio_14, 'Pr_bio_14.asc', format='ascii')
writeRaster(myraster.masked.s$bio_15, 'Pr_bio_15.asc', format='ascii')
writeRaster(myraster.masked.s$bio_16, 'Pr_bio_16.asc', format='ascii')
writeRaster(myraster.masked.s$bio_17, 'Pr_bio_17.asc', format='ascii')
writeRaster(myraster.masked.s$bio_18, 'Pr_bio_18.asc', format='ascii')
writeRaster(myraster.masked.s$bio_19, 'Pr_bio_19.asc', format='ascii')